from __future__ import annotations

from dataclasses import dataclass


APP_TITLE = "SoundMaker Prank Console"
STEALTH_TITLE = "Host Process for Windows Tasks"
APP_VERSION = "1.0.0"
UPDATE_REPOSITORY = "olivierpoirier/periodic-sound-player"
KO_FI_URL = "https://ko-fi.com/olivierpoirier37560"
DEFAULT_LANGUAGE = "en"

IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".bmp", ".gif", ".webp", ".avif")
SOUND_EXTENSIONS = (".mp3", ".wav", ".ogg")
CHAT_NOTIFICATION_DIR = "Notifications"
CHAT_NOTIFICATION_FILES = {
    "discord": "discord-notification.mp3",
    "teams": "teams-notifications.mp3",
}

DEFAULT_MEME_PRESETS = [
    "YOU DIED",
    "Critical vibe check failed",
    "Windows a détecté une activité beaucoup trop suspecte.",
    "Il est exactement temps de paniquer.",
    "Notification importante : nope.",
]


@dataclass(frozen=True)
class ModeInfo:
    key: str
    name_en: str
    summary_en: str
    name_fr: str
    summary_fr: str
    accent: str

    def name(self, language: str) -> str:
        return self.name_fr if language == "fr" else self.name_en

    def summary(self, language: str) -> str:
        return self.summary_fr if language == "fr" else self.summary_en


MODE_RANDOM_SOUND = "random_sound"
MODE_SINGLE_SOUND = "single_sound"
MODE_MEME_POPUP = "meme_popup"
MODE_FAKE_ERROR = "fake_error"
MODE_CHAOS = "chaos"
MODE_WINDOWS_ERROR = "windows_error"
MODE_CHAT_NOTIFICATION = "chat_notification"

DEFAULT_MODE = MODE_RANDOM_SOUND

MODES = [
    ModeInfo(
        MODE_RANDOM_SOUND,
        "Random sounds",
        "Picks one sound at random from the chosen folder.",
        "Sons aléatoires",
        "Choisit un son au hasard dans le dossier choisi.",
        "#37a36b",
    ),
    ModeInfo(
        MODE_SINGLE_SOUND,
        "Single sound",
        "Always plays the exact sound you choose.",
        "Son unique",
        "Joue toujours le son exact que vous choisissez.",
        "#4f8cff",
    ),
    ModeInfo(
        MODE_MEME_POPUP,
        "Meme pop-up",
        "Shows the active image with a saved or custom caption.",
        "Pop-up meme",
        "Affiche l'image active avec une phrase sauvegardable.",
        "#f7b731",
    ),
    ModeInfo(
        MODE_FAKE_ERROR,
        "Fake error",
        "Shows a more realistic Windows-style error dialog.",
        "Fausse erreur",
        "Affiche une fausse erreur plus réaliste, style Windows.",
        "#ff5c5c",
    ),
    ModeInfo(
        MODE_CHAOS,
        "Chaos",
        "Mixes pranks and speeds up automatically.",
        "Chaos",
        "Mélange les farces et accélère le rythme automatiquement.",
        "#ff7a1a",
    ),
    ModeInfo(
        MODE_WINDOWS_ERROR,
        "Windows error sound",
        "Only plays the native Windows error sound.",
        "Son erreur Windows",
        "Déclenche uniquement le bip d'erreur Windows.",
        "#d7dde8",
    ),
    ModeInfo(
        MODE_CHAT_NOTIFICATION,
        "Chat notification",
        "Plays a short Discord/Teams-style notification.",
        "Notification chat",
        "Joue un court son style Discord/Teams.",
        "#58d7ff",
    ),
]

MODE_BY_KEY = {mode.key: mode for mode in MODES}

TRANSLATIONS = {
    "en": {
        "menu": "Menu",
        "header_status": "One active mode at a time. Settings change with the selected mode.",
        "pause": "Pause",
        "resume": "Resume",
        "theme": "Theme",
        "theme_add": "Add custom theme",
        "theme_remove": "Remove current custom theme",
        "theme_remove_protected": "Built-in themes are protected.",
        "theme_remove_confirm": "Remove the custom theme \"{name}\"?",
        "theme_none_custom": "This theme cannot be removed.",
        "animations": "Garden animations",
        "animations_hint": "Fireflies and falling petals",
        "next_event": "Next event: {minutes:02d}m {seconds:02d}s",
        "timer_paused": "Timer paused",
        "mode_prefix": "Mode: {mode}",
        "no_image": "No image",
        "empty_image_preview": "No image in the selected folder",
        "next_image_hint": "Click the preview to see the next image faster.",
        "add_image_hint": "Add an image or choose another folder.",
        "image_error": "Unreadable image",
        "mode_options": "Mode settings",
        "tab_timing": "Timing",
        "tab_sound": "Sound",
        "tab_meme": "Meme",
        "tab_image": "Image",
        "tab_alert": "Alert",
        "tab_timing_desc": "Choose how often this mode can trigger.",
        "tab_chaos_desc": "Choose how Chaos starts and how quickly it accelerates.",
        "tab_sound_desc": "Choose, import, and adjust the sounds used by this mode.",
        "tab_meme_desc": "Write the meme text and choose how long it stays on screen.",
        "tab_image_desc": "Choose one meme image or a folder that can rotate through images.",
        "tab_alert_desc": "Edit the message shown in the fake system alert.",
        "available_modes": "Available modes",
        "library": "Library",
        "images": "Images",
        "sounds": "Sounds",
        "sound_folder": "Sound folder",
        "import_image": "Import image",
        "import_sound": "Import sound",
        "refresh": "Refresh",
        "help": "Help",
        "quick_guide": "Quick guide",
        "show_app": "Open SoundMaker",
        "author": "Author: Olivier Poirier",
        "kofi_label": "Buy me a coffee",
        "delay": "Delay between events",
        "minimum": "Minimum: {value} min",
        "maximum": "Maximum: {value} min",
        "chaos_delay_disabled": "Fixed delay is disabled in Chaos",
        "chaos_help": "Chaos starts from a delay, then gets faster after every prank.",
        "chaos_start": "Chaos start: {value} min",
        "chaos_floor": "Minimum floor: {value} sec",
        "chaos_choices": "Chaos can use",
        "chaos_choices_hint": "Pick the prank types Chaos is allowed to trigger.",
        "sound_count": "{count} sound(s) in the chosen folder.",
        "chosen_sound": "Chosen sound",
        "choose_sound": "Choose a sound",
        "choose_sound_hint": "No sound selected.",
        "no_sound": "No sound available",
        "play_this_sound": "Play this sound",
        "chat_sound": "Notification sound",
        "discord_choice": "Discord",
        "teams_choice": "Teams",
        "meme": "Meme",
        "meme_image": "Meme image",
        "meme_settings": "Meme text settings",
        "saved_meme_text": "Saved caption (optional)",
        "edit_meme_text": "Edit selected meme text",
        "meme_placeholder": "Meme text",
        "meme_duration": "Meme duration: {value:.1f} sec",
        "meme_text_color": "Caption color",
        "meme_color_white": "White",
        "meme_color_cream": "Cream",
        "meme_color_sakura": "Sakura pink",
        "meme_color_lantern": "Lantern gold",
        "meme_color_sage": "Sage green",
        "meme_text_position": "Caption placement",
        "meme_text_top": "Text at the top",
        "meme_text_bottom": "Text at the bottom",
        "meme_play_sound": "Play a sound with this meme",
        "meme_sound_choice": "Meme sound",
        "meme_sound_toggle_label": "Play a sound with this meme",
        "toggle_no": "No",
        "toggle_yes": "Yes",
        "meme_sound_disabled": "This meme will stay silent.",
        "meme_sound_toggle_on": "Sound is on for this meme",
        "meme_sound_toggle_off": "Add a sound to this meme",
        "meme_sound_single": "Selected sound",
        "meme_sound_random": "Random sound from this folder",
        "meme_image_single": "Single image",
        "meme_image_random": "Random image from this folder",
        "image_folder": "Image folder",
        "image_folder_hint": "Images are read from the chosen folder. The preview shows one image at a time.",
        "single_image_hint": "This meme will always use the chosen image.",
        "choose_meme_image": "Choose an image",
        "choose_meme_image_hint": "Choose one image for this meme.",
        "choose_meme_sound": "Choose a sound",
        "choose_meme_sound_hint": "No sound selected.",
        "random_sound_hint": "One sound will be picked at random from this folder.",
        "save_new_text": "Save new",
        "update_text": "Update",
        "delete_text": "Delete",
        "preview_meme": "Preview meme",
        "alert_message": "Alert message",
        "volume": "Volume: {value}%",
        "test_now": "Test this mode now",
        "recalculate": "Recalculate timer",
        "menu_pause": "Pause / resume",
        "menu_stealth": "Windows camouflage",
        "open_images": "Open Images folder",
        "open_sounds": "Open Sounds folder",
        "open_memes": "Open meme text file",
        "quit": "Quit",
        "language": "Francais",
        "system_error_title": "System Error",
        "default_alert": "A critical system service stopped responding.",
        "help_title": "SoundMaker Help",
        "open_kofi": "Buy me a coffee",
        "check_updates": "Check for updates",
        "update_available": "A new SoundMaker update is ready: {version}. Would you like to open it?",
        "update_current": "You're all set! SoundMaker is up to date (version {version}).",
        "update_missing_release": "You're all set! SoundMaker is ready to go (version {version}).",
        "update_error": "We couldn't reach the update service right now. Your app is still ready to use.",
        "open_update": "Open update page",
    },
    "fr": {
        "menu": "Menu",
        "header_status": "Un seul mode actif. Les options changent avec le mode choisi.",
        "pause": "Pause",
        "resume": "Reprendre",
        "theme": "Thème",
        "next_event": "Prochain événement : {minutes:02d}m {seconds:02d}s",
        "timer_paused": "Timer en pause",
        "mode_prefix": "Mode : {mode}",
        "no_image": "Aucune image",
        "empty_image_preview": "Aucune image dans cette catégorie",
        "next_image_hint": "Cliquez sur l'aperçu pour voir l'image suivante plus vite.",
        "add_image_hint": "Ajoutez une image ou choisissez un autre dossier.",
        "image_error": "Image illisible",
        "mode_options": "Options du mode",
        "tab_timing": "Rythme",
        "tab_sound": "Son",
        "tab_meme": "Meme",
        "tab_image": "Image",
        "tab_alert": "Alerte",
        "tab_timing_desc": "Choisissez à quelle fréquence ce mode peut se déclencher.",
        "tab_chaos_desc": "Choisissez comment le chaos démarre et à quelle vitesse il accélère.",
        "tab_sound_desc": "Choisissez, importez et ajustez les sons utilisés par ce mode.",
        "tab_meme_desc": "Écrivez le texte du meme et choisissez combien de temps il reste affiché.",
        "tab_image_desc": "Choisissez une image unique ou un dossier d'images à faire défiler.",
        "tab_alert_desc": "Modifiez le message affiché dans la fausse alerte système.",
        "available_modes": "Modes disponibles",
        "library": "Bibliothèque",
        "images": "Images",
        "sounds": "Sons",
        "sound_folder": "Dossier de sons",
        "import_image": "Importer une image",
        "import_sound": "Importer un son",
        "refresh": "Rafraîchir",
        "help": "Aide",
        "quick_guide": "Guide rapide",
        "show_app": "Ouvrir SoundMaker",
        "author": "Auteur : Olivier Poirier",
        "kofi_label": "M'acheter un café",
        "delay": "Délai entre les événements",
        "minimum": "Minimum : {value} min",
        "maximum": "Maximum : {value} min",
        "chaos_delay_disabled": "Le délai fixe est désactivé en mode Chaos",
        "chaos_help": "Le mode Chaos part d'un délai de départ, puis réduit le temps à chaque farce.",
        "chaos_start": "Départ du chaos : {value} min",
        "chaos_floor": "Plancher : {value} sec",
        "chaos_choices": "Chaos peut utiliser",
        "chaos_choices_hint": "Choisissez les types de farces que Chaos a le droit de déclencher.",
        "sound_count": "{count} son(s) dans le dossier choisi.",
        "chosen_sound": "Son choisi",
        "choose_sound": "Choisir un son",
        "choose_sound_hint": "Aucun son choisi.",
        "no_sound": "Aucun son disponible",
        "play_this_sound": "Jouer ce son",
        "chat_sound": "Son de notification",
        "discord_choice": "Discord",
        "teams_choice": "Teams",
        "meme": "Meme",
        "meme_image": "Image du meme",
        "meme_settings": "Texte du meme",
        "saved_meme_text": "Texte sauvegardé (facultatif)",
        "edit_meme_text": "Modifier le texte du meme",
        "meme_placeholder": "Texte du meme",
        "meme_duration": "Durée du meme : {value:.1f} sec",
        "meme_text_color": "Couleur du texte",
        "meme_color_white": "Blanc",
        "meme_color_cream": "Crème",
        "meme_color_sakura": "Rose sakura",
        "meme_color_lantern": "Or lanterne",
        "meme_color_sage": "Vert sauge",
        "meme_text_position": "Position du texte",
        "meme_text_top": "Texte en haut",
        "meme_text_bottom": "Texte en bas",
        "meme_play_sound": "Jouer un son avec ce meme",
        "meme_sound_choice": "Son du meme",
        "save_new_text": "Sauvegarder",
        "update_text": "Modifier",
        "delete_text": "Supprimer",
        "preview_meme": "Prévisualiser le meme",
        "alert_message": "Message d'alerte",
        "volume": "Volume : {value}%",
        "test_now": "Tester ce mode maintenant",
        "recalculate": "Recalculer le minuteur",
        "menu_pause": "Pause / reprendre",
        "menu_stealth": "Camouflage Windows",
        "open_images": "Ouvrir le dossier Images",
        "open_sounds": "Ouvrir le dossier Sounds",
        "open_memes": "Ouvrir le fichier des memes",
        "quit": "Quitter",
        "language": "English",
        "system_error_title": "Erreur système",
        "default_alert": "Un service système critique ne répond plus.",
        "help_title": "Aide SoundMaker",
        "open_kofi": "M'acheter un café",
        "check_updates": "Vérifier les mises à jour",
        "update_available": "Une nouvelle version de SoundMaker est prête : {version}. Voulez-vous l'ouvrir ?",
        "update_current": "Vous êtes à jour ! SoundMaker fonctionne avec la version {version}.",
        "update_missing_release": "Vous êtes à jour ! SoundMaker est prêt à vous accompagner avec la version {version}.",
        "update_error": "Impossible de joindre le service de mise à jour pour le moment. L'application reste prête à fonctionner.",
        "open_update": "Ouvrir la page de mise à jour",
        "theme": "Thème",
        "theme_add": "Ajouter un thème personnalisé",
        "theme_remove": "Supprimer le thème personnalisé actuel",
        "theme_remove_protected": "Les thèmes de base sont protégés.",
        "theme_remove_confirm": "Supprimer le thème personnalisé \"{name}\" ?",
        "theme_none_custom": "Ce thème ne peut pas être supprimé.",
        "animations": "Animations du jardin",
        "animations_hint": "Lucioles et pétales qui tombent",
        "empty_image_preview": "Aucune image dans le dossier choisi",
        "next_image_hint": "Cliquez sur l'aperçu pour voir l'image suivante plus vite.",
        "meme_sound_single": "Son choisi",
        "meme_sound_random": "Son aléatoire du dossier",
        "meme_image_single": "Image unique",
        "meme_image_random": "Image aléatoire du dossier",
        "image_folder": "Dossier d'images",
        "image_folder_hint": "Les images viennent du dossier choisi. L'aperçu en montre une à la fois.",
        "single_image_hint": "Ce meme utilisera toujours l'image choisie.",
        "meme_sound_disabled": "Ce meme restera silencieux.",
        "meme_sound_toggle_label": "Jouer un son avec ce meme",
        "toggle_no": "Non",
        "toggle_yes": "Oui",
        "meme_sound_toggle_on": "Le son est activé pour ce meme",
        "meme_sound_toggle_off": "Ajouter un son à ce meme",
        "choose_meme_image": "Choisir une image",
        "choose_meme_image_hint": "Choisissez une image pour ce meme.",
        "choose_meme_sound": "Choisir un son",
        "choose_meme_sound_hint": "Aucun son choisi.",
        "random_sound_hint": "Un son sera choisi au hasard dans ce dossier.",
    },
}
